language: perl
perl:
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
before_install:
    # install prereqs
    - "cpanm Moose"
    - "cpanm Moose::Role"
    - "cpanm namespace::autoclean"
    - "cpanm Try::Tiny"
    - "cpanm YAML::XS"
    - "cpanm Devel::Cover::Report::Coveralls"
script:
    perl Makefile.PL && make test && cover -test -report coveralls
